# Base image
FROM node:23.7.0 AS builder

# Set working directory
WORKDIR /app

# Copy frontend code
COPY /src/frontend/ .

# Install dependencies and build
RUN npm install && npm run build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist /usr/share/nginx/html

# Expose frontend port
EXPOSE 80

# Serve the build directory
CMD ["nginx", "-g", "daemon off;"]
